
@startuml
actor User
participant System

User -> System: initiateQuiz(numOfQuestions)
System -> System: fetch questions
System --> User: generateQuiz(numOfQuestions)

loop for each question
    User --> System: answerquestion(answer)
    System -> System: evaluateAnswer(answer)
    System --> User: displayanswer()
end

alt not all questions answered
    System --> User: displayMessage("not all questions answered")
else all questions answered
    User -> System: submitQuiz(answers)
    System -> System: saveQuizResults()
    System --> User: displaygrade(score)
end
@enduml