@startuml
actor "User" as User
rectangle "Banana brain learning" {
    usecase "Signup"
    usecase "Login"
    usecase "View courses"
    usecase "enroll in a course"
    usecase "Select topics for a course"
    usecase "Answer questions for a topic"
    usecase "Take quizzes for a course"
    usecase "View leaderboards"
    usecase "Collect reward badge"
}

User -- "Signup"
User -- "Login"
User -- "View courses"
User -- "enroll in a course"
User -- "Select topics for a course"
User -- "Answer questions for a topic"
User -- "View leaderboards"
User -- "Take quizzes for a course"
User -- "Collect reward badge"



@enduml

