@startuml
class User
{
    +userId
    +username
    +password
    +age
    +email
    +total_points
    +badges
}
class Course
{
    +courseId
    +CourseName
    +title
    +description
    +topics
    +prerequisites
}
class Topic
{
    +topicId
    +title
    +description
    +questions
}
class Question
{
    +questionId
    +text
    +options
    +correctAnswer
}
class Quiz
{
    +quizId
    +title
    +questions
    +totalScore
    +userId
}
class Leaderboard
{
    +topUsers
}

class Badge
{
    +title
    +description
    +criteria
}
class Enrollment
{
    +userId
    +courseId
    +date
    +completionStatus
}
class TopicQuestions
{
    +questionId
    +question
    +correctAnswer
}
class Authorization
{
    +username
    +password
    +email
    +age
    +status
}
class QuizGenerator
{
    +number_of_questions
}
User "1" -- "0..*" Enrollment : participates in
User "1" -- "1" Leaderboard : views
Enrollment "1" -- "1" Course : enrolls in
Course "1" -- "0..*" Topic : contains
Topic "1" -- "10..40" Question : contains
User "1" -- "0..*" Quiz : takes
Quiz "1" -- "10..20*" Question : contains
User "1" -- "0.." Badge : earns
Authorization "1" -- "1" User : manages
QuizGenerator "1" -- "*" Quiz : generates
Topic "1" -- "0..*" TopicQuestions : contains
Badge "1" -- "1" Course : associated with
User "1" -- "0..*" TopicQuestions : solves
Question "10..40" -- "1" TopicQuestions : contains
@enduml